Feature/user sign in and sign up
yuanliif/ac-twitter pull request #12
Opened 2022-02-26 08:10 UTC by AlisonLeng

新增 UserSignIn 頁面及 UserSignUp 頁面

2022-02-26 08:22 UTC, erase2004 commented
和下述PR都有對GeneralInput進行修改，review與併入的順序建議是PR 11優先
[修正GeneralInput顯示問題 & 更新使用者Profile頁](https://github.com/yuanliif/AC-twitter/pull/11)

2022-02-26 15:50 UTC, erase2004 requested changes
1. 登入頁那幾個樣式沒有被套用到，CSS需要再調整
![Snipaste_2022-02-26_22-59-14](https://user-images.githubusercontent.com/1367757/155849495-67aff372-ce33-4022-805c-550693d8f27c.png)
 2. 註冊頁的名稱輸入沒有顯示數字的要求
![Snipaste_2022-02-26_23-41-00](https://user-images.githubusercontent.com/1367757/155849536-1985f778-1b64-4ced-ab65-3411cd32eb76.png)
 3. 登入頁的驗證錯誤顯示位置和註冊頁的登入顯示位置都有問題
 4. 目前功能大致是OK，但上述明顯問題仍需調整

2022-02-26 15:50 UTC, erase2004 commented on src/views/UserSignIn.vue
> +        ({ status, message } = this.checkPassword(this.data.password))
這邊密碼檢查的錯誤塞到account底下，
所以預期是所有的錯誤都顯示在帳號框底下?

2022-02-26 15:50 UTC, erase2004 commented on src/views/UserSignUp.vue
> +
這一堆輸入的檢查，最後錯誤訊息都放到account底下顯示了，
這是預期要的結果？

2022-02-27 05:01 UTC, AlisonLeng commented
1. 修正了 SignIn 頁面中 註冊 Alphitter 及 後台登入 按鈕未套用到 CSS 樣式的問題
2. 更改 SignIn 頁面中輸入驗證的錯訊息顯示位置
3. 更改 SignIn 頁面中輸入驗證的錯訊息顯示位置

2022-02-27 05:41 UTC, AlisonLeng commented
1. 更新來自遠端的 branch
2. 設定使用者登入頁的 token

2022-02-27 06:11 UTC, erase2004 approved these changes
大致可以使用

2022-02-27 06:11 UTC, erase2004 commented on src/views/UserSignIn.vue
> +    justify-content: end;
建議調整為`flex-end`，end的屬性較為廣泛，可被套用的對象較多，flex-end則僅限flex元素

2022-02-27 06:11 UTC, erase2004 commented on src/views/UserSignUp.vue
> +    handleCancel (e) {
其實這一個按鈕的設計目的應該是「取消註冊，返回登入頁」

2022-02-27 06:11 UTC, merged