Feature/following and follower
yuanliif/ac-twitter pull request #19
Opened 2022-02-28 08:52 UTC by AlisonLeng

新增 follower & following 頁面 及 更新 UserSignUp 的取消按鈕功能

2022-02-28 18:12 UTC, erase2004 requested changes
類似的結構，錯誤也就被複製了

2022-02-28 18:12 UTC, erase2004 commented on src/views/Following.vue
> +    this.fetchFollowings()
遺漏傳入參數

2022-02-28 18:12 UTC, erase2004 commented on src/views/Follower.vue
> +    this.fetchFollowers()
遺漏傳入參數

2022-02-28 18:12 UTC, erase2004 commented on src/components/FollowersList.vue
> +        <FollowControlButton :initial-user="user" />
這邊傳入數值錯誤，按鈕的對象應該是對應的跟隨者，而不是都同一個不明的`user`

2022-02-28 18:12 UTC, erase2004 commented on src/components/FollowingsList.vue
> +        <FollowControlButton :initial-user="user" />
這邊傳入數值錯誤，按鈕的對象應該是對應的跟隨者，而不是都同一個不明的`user`

2022-02-28 18:12 UTC, erase2004 commented on src/views/Follower.vue
> +        if (response.status !== 200) {
現在`response`回傳code都是`200`了，這個敘述基本上永遠為`true`

2022-02-28 18:12 UTC, erase2004 commented on src/views/Following.vue
> +        if (response.status !== 200) {
現在`response`回傳code都是`200`了，這個敘述基本上永遠為`true`

2022-02-28 18:12 UTC, erase2004 commented on src/views/UserSignUp.vue
> +      <router-link
回到上一頁的作法未必總是合理，進入的方式不只一種

2022-03-01 04:43 UTC, erase2004 requested changes
1. 導覽列路由寫法錯誤
2. FolloweControlButton傳入的參數依舊有錯

建議：**多多複習教材，增加與語法的熟悉與掌握度**

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowersList.vue
> +        <FollowControlButton :initial-user="{followers}" />
這個數值還是有問題的，沒有傳入FollowControlButton所要操作的`user`型態資料

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowersList.vue
> +      user: {
`user`資料沒再使用了

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowingsList.vue
> +        <FollowControlButton :initial-user="{followings}" />
這個數值還是有問題的，沒有傳入FollowControlButton所要操作的`user`型態資料

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowingsList.vue
> +      user: {
`user`資料沒再使用了

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowerAndFollowingNav.vue
> +        to="/user/:id"
檢查才發現這路由對象這樣寫是有問題的

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowerAndFollowingNav.vue
> +        to="/user/:id/followers"
檢查才發現這路由對象這樣寫是有問題的

2022-03-01 04:43 UTC, erase2004 commented on src/components/FollowerAndFollowingNav.vue
> +        to="/user/:id/followings"
檢查才發現這路由對象這樣寫是有問題的

2022-03-02 11:55 UTC, yuanliif approved these changes
OK

2022-03-02 11:56 UTC, merged